### ISSUE TITLE
Client kicked from server due to NoClassDefFoundError (Tombstone 2.9.6 / Modern Skyblock 3 Departed 3.4.1.2)

### ISSUE THREAD

**Issue by merphle** [Corail31/tombstone_lite#10]
I'm running a Modern Skyblock 3 Departed server for a few folks. We recently upgraded from pack version 3.3.1.4 to 3.4.1.2, and one of the players has been getting kicked off the server exactly 10 minutes after logging in. The server debug.log shows the below helpful information.

```
[18:19:01] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /[IP address]:49753
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class ovh.corail.tombstone.core.SupportStructures
        at ovh.corail.tombstone.item.ItemLostTablet.wakeUpMagic(ItemLostTablet.java:84) ~[ItemLostTablet.class:?]
        at ovh.corail.tombstone.item.ItemLostTablet.func_77663_a(ItemLostTablet.java:75) ~[ItemLostTablet.class:?]
        at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526) ~[aip.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363) ~[aec.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more

```

He examined his inventory and noticed that he was carrying an Ancient Tablet from Corail Tombstone. He has no idea how it got there. He just put it into a chest and it disappeared. Hopefully that's the last of the client-kicking. I'm just reporting it here in case it's of any use to you.

**Comment by Corail31** [comment]
oh thanks for this report, it's related to the recent changes on theses tablets, and i will make this version no more downloadable.
i'll probably fix it tomorrow (as a provisory fix, you can set the % chance to have this tablet in the config file to 0%)

**Comment by merphle** [comment]
Thanks! I'll update it now for my server - maybe the MS3D folks might be interested in hearing about this too.

**Comment by Corail31** [comment]
Could you provide me the exact log ?

**Comment by Corail31** [comment]
Fix in 2.9.7 (biomes not present)
=> the 2.9.7 is only required on server side and accepts both 2.9.6 & 2.9.7 remote versions)

**Comment by merphle** [comment]
That stack trace I posted in my OP is pretty much all there is -- just a couple of standard Minecraft lines after that indicating that the user experienced an Internal Server Error, and left the game.

**Comment by Corail31** [comment]
@merphle btw, you can contact me easily on modern skyblock discord if needed :)

**Comment by merphle** [comment]
Just what I need, yet another Discord to follow. ;) Thanks, I hopped in.
