### ISSUE TITLE
Players falling outside of world loses graves

### ISSUE THREAD

**Issue by Akitori** [Corail31/tombstone_lite#14]
Heya. Randomly a player of mine fell farther than normal into the void (due to a combination of scaling health and a regeneration buff). 

Their gravestone is unable to be found, i have no way of accessing it as far as i'm aware, so is there some way to undo it? To find the items stored?

Also as a fix, maybe make it so that if any person dies below -1 it tps the gravestone to 1 or higher?

**Comment by Corail31** [comment]
Please, don't let a feel that my mod isn't working with world border,
If you fall in the void, the grave is placed at y = 1 minimum (in fact the mod follow "isValidWorldPos")
If you do bad things with "modded features", i can't help you.

**Comment by Akitori** [comment]
Except no it didn't. My friend fell to like -1313 (they fell a long time) and the grave didn't show up at y=1.

**Comment by Corail31** [comment]
In fact y=1 was for example, the event looks for the range to spawn, and go up to find valid world pos.
If you could reproduce it, with the config option to log grave pos, or provide me infos about what return the command about lastGrave, i could understand better what happened :) (and if you received a message about no placement for grave)

**Comment by Akitori** [comment]
Here's the log thrown at me from logs.latest. 

`java.lang.NullPointerException: null
	at ovh.corail.tombstone.handler.EventHandler.buildTombstone(EventHandler.java:196) ~[EventHandler.class:?]
	at ovh.corail.tombstone.handler.EventHandler.onLivingDrops(EventHandler.java:125) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_87_EventHandler_onLivingDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:510) ~[oq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1038) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:645) ~[oq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_174812_G(EntityLivingBase.java:158) ~[vp.class:?]
	at net.minecraft.command.CommandKill.func_184881_a(SourceFile:35) ~[cp.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[19:34:25] [main/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[19:34:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4945ms behind, skipping 98 tick(s)
[19:34:33] [main/INFO]: [CHAT] Saved screenshot as 2018-01-05_19.34.33.png
[19:34:39] [Server thread/INFO]: [TemporalWanderer: Set own game mode to Creative Mode]
[19:34:39] [main/INFO]: [CHAT] Your game mode has been updated to Creative Mode
[19:35:04] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2727ms behind, skipping 54 tick(s)
[19:35:04] [Server thread/INFO]: Scanning for legacy world dragon fight...
[19:35:04] [Server thread/INFO]: Found that the dragon has not yet been killed in this world.
[19:35:05] [Server thread/INFO]: Found that there's a dragon still alive (EntityDragon['Ender Dragon'/148775, l='New World----', x=-48.80, y=84.13, z=-23.78])
[19:35:05] [Server thread/INFO]: But we didn't have a portal, let's remove it.
[19:35:11] [main/INFO]: [CHAT] /TBShowLastGrave, /TBTeleportToGrave, /TBTeleportToPlayer
[19:35:13] [main/INFO]: [CHAT] Last known grave has been set at pos [109, -1368, -5] in dim [1]
[19:35:17] [main/INFO]: [CHAT] Saved screenshot as 2018-01-05_19.35.16.png`

Also a screenshot of my last grave position
![2018-01-05_19 35 16](https://user-images.githubusercontent.com/24502131/34635063-11fee1f0-f250-11e7-86a9-88ebab6b2f5a.png)

Hope this helps

**Comment by Corail31** [comment]
Yes, it helps and i will make tests to reproduce it :)
