### ISSUE TITLE
Crash 1.12.2 F2709 V2981.12 - Cannot get property PropertyBool{name=has_soul,[...]}

### ISSUE THREAD

**Issue by alxcool** [Corail31/tombstone_lite#15]
single player 1.12.2 Forge 2709
Coral+tombstone-2.9.8-1.12.jar

Hi! I really enjoy playing this mod, unfortunate I've got a crash this morning. I don't know If I am using the latest mod version too. Note also that this crash file contain many mods, so let me know If I should reproduce this with fewer mods if it could help.

### How to reproduce
https://paste.dimdev.org/oyehisuwiz.mccrash

I was harvesting a hand crafted grave using a silk touch shovel, (how work the disenchant book?). Then I did a few more things, like using bone meal, interaction with chests before the creation of this server crash

My best guess is that the server got latency then when it tried to check his function, "has soul", the block was moved. So it check if the replaced block,  air block, instead have that property.

### The latest.log a few lines...

List of previous lines just before the crash... Or what was I doing.
[11:13:26] [Netty Server IO #1/INFO] [CodeChickenLib-ConfigSync]: Sending config sync packet to player.
[11:13:26] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[11:13:26] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[11:13:26] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Al_Cool[local:E:677413fc] logged in with entity id 371 at (109.86644496084084, 79.0, -192.1646120876277)
[11:13:26] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Al_Cool joined the game
[11:13:27] [Server thread/INFO] [Waila]: Player EntityPlayerMP['Al_Cool'/371, l='Vacations', x=109.87, y=79.00, z=-192.16] connected. Sending ping
[11:13:27] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[11:13:31] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Saving and pausing game...
[11:13:31] [Netty Local Client IO #0/INFO] [Waila]: Received server authentication msg. Remote sync will be activated
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.bibliocraftmod.com/vcheck/version.txt
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivileged(Native Method)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.net.URL.openStream(Unknown Source)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck.getNetVersion(VersionCheck.java:58)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at jds.bibliocraft.VersionCheck$1.run(VersionCheck.java:46)
[11:13:31] [Thread-18/INFO] [STDERR]: [jds.bibliocraft.VersionCheck:getNetVersion:88]: 	at java.lang.Thread.run(Unknown Source)
[11:13:31] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Vacations'/overworld
[11:13:32] [main/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 480 advancements
[11:13:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Vacations'/Tropics
[11:13:33] [Server thread/INFO] [net.minecraft.world.chunk.storage.AnvilChunkLoader]: ThreadedAnvilChunkStorage (Vacations): All chunks are saved
[11:13:33] [Server thread/INFO] [net.minecraft.world.chunk.storage.AnvilChunkLoader]: ThreadedAnvilChunkStorage (TROPICS): All chunks are saved
[11:13:34] [Thread-8/INFO] [STDOUT]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: -1_-1 1
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 10
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at cpw.mods.ironchest.common.blocks.shulker.BlockIronShulkerBox.func_176203_a(BlockIronShulkerBox.java:190)
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2693)
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[11:13:34] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Unknown Source)
[11:13:34] [Thread-8/INFO] [STDOUT]: [xaero.map.MapLoader:loadBlockColourFromTexture:743]: Block file not found: minecraft:air
[11:13:35] [Thread-8/INFO] [STDOUT]: [xaero.map.MapSaveLoad:loadRegion:464]: Region failed to load: 0_-1 1
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: java.lang.ArrayIndexOutOfBoundsException: 10
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at cpw.mods.ironchest.common.blocks.shulker.BlockIronShulkerBox.func_176203_a(BlockIronShulkerBox.java:190)
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at net.minecraft.block.Block.func_176220_d(Block.java:2693)
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.Misc.getStateById(Misc.java:22)
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadPixel(MapSaveLoad.java:774)
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.loadRegion(MapSaveLoad.java:440)
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at xaero.map.MapSaveLoad.run(MapSaveLoad.java:600)
[11:13:35] [Thread-8/INFO] [STDERR]: [xaero.map.MapSaveLoad:loadRegion:465]: 	at java.lang.Thread.run(Unknown Source)
[11:13:35] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 8674ms behind, skipping 173 tick(s)
[11:14:11] [Aromabackup-Backup/INFO] [AromaBackup]: Deleted backup Backup--Vacations--2018-06-26--11-13.zip.
[11:14:11] [Aromabackup-Backup/OFF] [Aroma1997Core]: Message to players; Message: World Backup done!
[11:14:11] [Aromabackup-Backup/INFO] [net.minecraft.server.MinecraftServer]: [§1AromaBackup§r] World Backup done!
[11:14:11] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [§1AromaBackup§r] World Backup done!

### A few line after the crash
[11:19:48] [main/ERROR] [net.minecraft.client.Minecraft]: ########## GL ERROR ##########
[11:19:48] [main/ERROR] [net.minecraft.client.Minecraft]: @ VanillaFix GUI Loop
[11:19:48] [main/ERROR] [net.minecraft.client.Minecraft]: 1280: Invalid enum

Let me know If I could help some more ;)
[latest.log](https://github.com/Corail31/tombstone_lite/files/2141923/latest.log)

**Comment by Corail31** [comment]
Honestly i have no idea why you have an air blockstate at the place the grave... "by magic without doing anything as you said"

**Comment by alxcool** [comment]
Thk for the fast reply! I'm aware of this error in my config files. I keep changing whats mods I keep or not active, so eventually I create config line for recycler for mods who eventually become disabled before initialization. Actually I have a big user-defined recipes, over 8k lines, or 1000 recipes. I really enjoy Recycler I just din't took time to update that mods to its version 3 yet. Eventually I may like to share some already filled config file as compatibility about some popular mods that I know and use.
I'l check that disenchantment book agains, thats look really cool ^^. Keep the good work.

**Comment by Corail31** [comment]
You may try the v3 of Recycler, there're some useful changes like an ingame button to automatically discover the recipe and an input inventory ;)

**Comment by alxcool** [comment]
Sure I will try it^^ thk, and I've fixed the obvious error in my config files. ex a tech mod who replace equivalent items when I use the addRecipe function. I though 380 was the line's number, but it was the amount of recipes to fix. Sorry for that, I've also removed mod's lines who are currently disabled, and placed them aside in an another area on my computer. Should we close this topic?

**Comment by Corail31** [comment]
Fix in 2.9.9
