### ISSUE TITLE
runData crash

### ISSUE THREAD

**Issue by mickelus** [Corail31/tombstone_lite#162]
I'm using data providers to generate data for enchantment compatability in https://github.com/mickelus/tetra, I'm trying to add support for corail tombstone https://github.com/mickelus/tetra/issues/114 but runData crashes when I have corail tombstone in my setup, with the following exception:

> [modloading-worker-2/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: tombstone, class ovh.corail.tombstone.ModTombstone
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$3(AutomaticEventSubscriber.java:70) ~[?:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_121] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:57) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) ~[?:31.1] {re:classloading}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_121] {}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_121] {}
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_121] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_121] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_121] {}
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_121] {}
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_121] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_121] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_121] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_121] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_121] {}
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fml.client.registry.ClientRegistry.registerKeyBinding(ClientRegistry.java:59) ~[?:?] {re:classloading}
	at ovh.corail.tombstone.event.ClientEventHandler.<clinit>(ClientEventHandler.java:83) ~[?:4.3.4] {re:classloading,pl:runtimedistcleaner:A}
	... 19 more

Here's the full log https://gist.github.com/mickelus/4b3681ecfcd7989e053672f6ae375da8

**Comment by Corail31** [comment]
@mickelus Honestly, i'm passed today on your github and i saw all the issues about theses enchantment informations, and i didn't understand why you need something that is present in code.
But as i don't know your mod, i didn't try to look further. I don't provide support to load my mod in a workspace, except if it's the api.
