### ISSUE TITLE
ItemFamiliarStone problem on use

### ISSUE THREAD

**Issue by makegodhere** [Corail31/tombstone_lite#201]
### Minecraft Version

1.12.2

### Forge Version

14.23.5.2860

### Corail Tombstone Version

4.6.2

### What happened?

On server iv got this error in logs and player hbeen kicked.
After login on server - familiar stone not disappeared but wolf back to life.
```
[22:57:48] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /{IP AND PORT CLIENT}
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: java.lang.NoSuchMethodError: ovh.corail.tombstone.helper.LangKey.getText([Ljava/lang/Object;)Ljava/lang/String;
        at ovh.corail.tombstone.item.ItemFamiliarStone.func_77654_b(ItemFamiliarStone.java:95) ~[ItemFamiliarStone.class:?]
        at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
        at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2789) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2688) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
[22:57:48] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: USER lost connection: Internal server error
```

On singleplayer iv got this in chat (no crash game):
![image](https://github.com/Corail31/tombstone_lite/assets/28805838/4f9b4373-95ef-4e10-8cb1-aa94fffdb138)

Both errors happens in modpack and single tombstone mod.

### Gametype

Singleplayer, Dedicated Server

### Happen by testing with only Corail Tombstone (required)

Yes

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
As a precision, Familiar Stone doesn't disappear if you play in creative mode.
