### ISSUE TITLE
Random ticking entity crash. (Perhaps related to a Receptable with a Familar?)

### ISSUE THREAD

**Issue by Gbergz** [Corail31/tombstone_lite#221]
### Minecraft Version

1.20.1

### Forge Version

47.2.17

### Corail Tombstone Version

8.6.5

### What happened?

Server randomly crashed with "Ticking entity". Not entirely sure what triggered other than the ticking entity part and maybe because of a "Receptable".

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs rarely

### Other relevant mods

Modpack is TNP Limitless 7: https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7

### Log Link

https://gist.githubusercontent.com/Gbergz/6783d27afc21f69f8214b296a877647b/raw/02f26b5692c3a10e4478b2518bce3a8da0a9da78/gistfile1.txt

```
	at net.minecraft.world.level.storage.PlayerDataStorage.m_78435_(PlayerDataStorage.java:58) ~[server-1.20.1-20230612.114412-srg.jar%231383!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.irons_spellbooks.json:DataFixPlayerDataStorageMixin,pl:mixin:A}
	at ovh.corail.tombstone.helper.EntityHelper.loadPlayerData(EntityHelper.java:265) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:mixin,re:classloading}
	at ovh.corail.tombstone.helper.EntityHelper.getOfflinePlayer(EntityHelper.java:273) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:mixin,re:classloading}
	at ovh.corail.tombstone.item.ItemFamiliarReceptacle.captureSoul(ItemFamiliarReceptacle.java:221) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:classloading}
	at ovh.corail.tombstone.event.EventHandler.onPreventDeath(EventHandler.java:411) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:classloading}
	at ovh.corail.tombstone.event.__EventHandler_onPreventDeath_LivingDamageEvent.invoke(.dynamic) ~[tombstone-1.20.1-8.6.5.jar%231325!/:8.6.5] {re:classloading,pl:eventbus:B}
```

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
"com.bawnorton.neruina".

**Comment by Gbergz** [comment]
Neruina just prevents crashes by deleting the entity, sometimes it fails, but the ticking entity crash still happens with it disabled.

**Comment by Gbergz** [comment]
I can try to get you a crash report without Neruina mentioned if it matters, but it does still happen without that mod.
Reported here too: https://github.com/Bawnorton/Neruina/issues/65

**Comment by Corail31** [comment]
You have too much mods using mixing in your report to really locate the problem.
The only hint that i can recommand you to test is if a player has a tamed creature and log off and the creature is killed after on a dedicated server (without others mods) which load the offline player to see if he has a receptable to catch it.
Edit: i'll re-open the issue if it's related to the loading of the offline player.

**Comment by Gbergz** [comment]
Ah, thats annoying.

I will however try what you suggested to try and reproduce the issue with just Tombstone and no other mods.

**Comment by Gbergz** [comment]
Been trying now in an instance with just Tombstone, couldn't reproduce it in the way you described.
Also hopped on the modpack to try it there aswell, nothing. hmm..
