### ISSUE TITLE
Crashes before entering world

### ISSUE THREAD

**Issue by ryuujo1573** [Corail31/tombstone_lite#35]
### Minecraft Version

1.12.2

### Forge Version

2854

### Corail Tombstone Version

4.0.0 / 4.5.1

### What happened?

After "Building Terrain" and before see the world rendered, the game crashes with termination.

I think this might be a GPU/OpenGL issue, and any reply would be appreciated.

Without loading the Corail Tombstone mod, the game seemed to be frozen after "Building Terrain" disappeared. I'm trying to create a new save without the mod, which will be shown later.

### Environment: 

* CPU: Apple Silicon, M1;
* MultiMC: 0.6.14;
* LWJGL: 3.2.2
* Forge: 14.23.5.2854
* Minecraft: 1.12.2

### Server crash report

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Corail Tombstone (tombstone)
Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.addCallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureCallback;)V
	at ovh.corail.tombstone.helper.Helper.loadContributors(Helper.java:511)
	at ovh.corail.tombstone.ModTombstone.onServerStarted(ModTombstone.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at ......
```

Full content here: [Crash Report](https://pastebin.com/4D8kB5bb)

### Log Link

https://pastebin.com/4D8kB5bb

### Gametype

Singleplayer, Dedicated Server

### Happen with only Corail Tombstone

Yes

### Valid Launcher

- [X] Yes

**Comment by ryuujo1573** [comment]
Well, the game got stuck for creating a new world

**Comment by ryuujo1573** [comment]
Thank you for attention. 

I figured out the crash happens without any mod, whose log looks like:
```
java.lang.NoSuchMethodError: com.google.common.util.concurrent.Futures.addCallback(Lcom/google/common/util/concurrent/ListenableFuture;Lcom/google/common/util/concurrent/FutureCallback;)V
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:141)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:748)
...
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (aarch64) version 12.0.1
	Java Version: 1.8.0_282, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 1511370360 bytes (1441 MB) / 2004353024 bytes (1911 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms1024m -Xmx4096m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                                  | Signature                                |
	|:------ |:--------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Apple M1
[16:03:33] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /Applications/MultiMC.app/Data/instances/SevTech-Ages_3.2.1/minecraft/crash-reports/crash-2021-12-10_16.03.33-client.txt
[16:03:33] [Client Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[16:03:33] [Client Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving players
```
With `org.lwjgl.json`
```json
{
    "components": [
        {
            "cachedName": "LWJGL 3",
            "cachedVersion": "3.2.2",
            "dependencyOnly": true,
            "uid": "org.lwjgl",
            "version": "2.9.4-nightly-20150209"
        },
        {
            "cachedName": "Minecraft",
            "cachedRequires": [
                {
                    "suggests": "2.9.4-nightly-20150209",
                    "uid": "org.lwjgl"
                }
            ],
            "cachedVersion": "1.12.2",
            "important": true,
            "uid": "net.minecraft",
            "version": "1.12.2"
        },
        {
            "cachedName": "Forge",
            "cachedRequires": [
                {
                    "equals": "1.12.2",
                    "uid": "net.minecraft"
                }
            ],
            "cachedVersion": "14.23.5.2854",
            "uid": "net.minecraftforge",
            "version": "14.23.5.2854"
        }
    ],
    "formatVersion": 1
}
```
```
Exception in thread "Client Shutdown Thread" 
```

If you would like to help me, it would make my day  :)
and thanks for any response and excuse my poor English orz..

**Comment by Corail31** [comment]
If it happens without the mod, it's on Forge to ask for questions. I suppose it's related to the guava version and deprecation.
NB: i don't use anymore this code in upper versions so, in a future version, it will be removed too in 1.12.2 (this doesn't change your actual trouble with Forge).
Edit: if it can help you, the method was removed in guava 26 in favour of an another method using an executor.

**Comment by ryuujo1573** [comment]
Thank you for your reply!
and there're sure some troubles with forge: 1.12.2 works well with Zulu-11.jre (arm64), while not with forge added. I'll try to figure out, thank you.
