### ISSUE TITLE
(Bug) Crash Rendering Screen

### ISSUE THREAD

**Issue by CrazyCowboy557** [Corail31/tombstone_lite#69]
When launching the game I get Rendering Screen crash even if this is the only mod. Here is my crash log:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 6/28/19 4:05 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraftforge.fml.ModList.size(ModList.java:164) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.BrandingControl.computeBranding(BrandingControl.java:59) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.BrandingControl.getBrandings(BrandingControl.java:68) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.BrandingControl.forEachLine(BrandingControl.java:77) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.MainMenuScreen.render(MainMenuScreen.java:248) ~[?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:358) ~[?:?] {pl:eventbus:A,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:554) ~[?:?] {pl:accesstransformer:B,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898) [?:?] {pl:accesstransformer:B,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:154) [?:?] {pl:object_holder_definalize:A,pl:runtime_enum_extender:A,pl:capability_inject_definalize:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.14.2-26.0.8.jar:26.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$289/1824837049.call(Unknown Source) [forge-1.14.2-26.0.8.jar:26.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) [modlauncher-2.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) [modlauncher-2.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-2.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:59) [modlauncher-2.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44) [modlauncher-2.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.ModList.size(ModList.java:164)
	at net.minecraftforge.fml.BrandingControl.computeBranding(BrandingControl.java:59)
	at net.minecraftforge.fml.BrandingControl.getBrandings(BrandingControl.java:68)
	at net.minecraftforge.fml.BrandingControl.forEachLine(BrandingControl.java:77)
	at net.minecraft.client.gui.screen.MainMenuScreen.render(MainMenuScreen.java:248)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:358)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.MainMenuScreen
	Mouse location: Scaled: (88, 131). Absolute: (266.000000, 395.000000)
	Screen size: Scaled: (342, 256). Absolute: (1024, 768). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:554)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$289/1824837049.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:59)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 588847816 bytes (561 MB) / 1649934336 bytes (1573 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Launched Version: forge-26.0.8
	LWJGL: 3.2.1 build 12
	OpenGL: Radeon 550 Series GL version 4.5.13542 Compatibility Profile Context 25.20.14021.6006, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by Corail31** [comment]
Sorry, but it's not the forge issues here, but Tombstone issues...
NB : if you use an old version of forge, they can't display the errors in a gui, even for things like minimal forge version required...
