### ISSUE TITLE
Exception Caught during firing event: null

### ISSUE THREAD

**Issue by itsdinkd** [Corail31/tombstone_lite#89]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Corail Tombstone Version

7.5.4

### What happened?

Playing game as normal and seeing this error caught since updating today it occurs on a regular basis on my pack

```
[01Oct2022 15:17:04.667] [ForkJoinPool.commonPool-worker-4/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 20
	Listeners:
		0: HIGHEST
		1: ASM: class ovh.corail.tombstone.event.ClientEventHandler handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		2: HIGH
		3: ASM: class dev.architectury.event.forge.EventHandlerImplClient event(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		4: NORMAL
		5: net.minecraftforge.eventbus.EventBus$$Lambda$2996/0x0000000800aa7330@42aa316f
		6: ASM: class harmonised.pmmo.events.ClientEventHandler tooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		7: ASM: class io.github.edwinmindcraft.calio.common.CalioEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		8: ASM: futurepack.client.ClientEvents@77815aad onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		9: ASM: org.cyclops.evilcraft.core.broom.BroomPartRegistry@7918b0e3 onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		10: ASM: org.cyclops.evilcraft.core.broom.BroomModifierRegistry@2d6fbcd onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		11: ASM: class com.legacy.blue_skies.client.events.SkiesClientEvents onRenderToolTip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$2996/0x0000000800aa7330@7d777def
		13: ASM: class limonblaze.originsclasses.common.event.PowerEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		14: ASM: class io.github.edwinmindcraft.apoli.common.ApoliPowerEventHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		15: ASM: class com.teammetallurgy.aquaculture.loot.FishWeightHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		16: ASM: class com.teammetallurgy.aquaculture.misc.AquaTooltip onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		17: ASM: class cofh.core.event.CoreClientEvents handleItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		18: ASM: class io.github.strikerrocker.vt.tweaks.SilkSpawner$ClientEvents onToolTipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		19: ASM: class cofh.thermal.core.event.TCoreClientEvents handleItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		20: net.minecraftforge.eventbus.EventBus$$Lambda$2996/0x0000000800aa7330@133c599a
		21: ASM: net.silentchaos512.gear.client.event.TooltipHandler@7d1d7104 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		22: ASM: class com.mna.events.ClientEventHandler onTooltipRender(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		23: ASM: class shadows.fastbench.ClientHandler tooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		24: ASM: class com.cazsius.solcarrot.client.TooltipHandler onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		25: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@3d8cd5af onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		26: ASM: class vectorwing.farmersdelight.client.event.TooltipEvents addTooltipToVanillaSoups(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		27: ASM: class vazkii.quark.base.client.handler.RequiredModTooltipHandler onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		28: ASM: class slimeknights.tconstruct.tools.client.ModifierClientEvents onTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		29: ASM: class com.simibubi.create.events.ClientEvents addToItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		30: ASM: class org.cyclops.cyclopscore.item.ItemInformationProvider onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		31: ASM: vazkii.quark.content.building.module.CelebratoryLampsModule@7a5cbcf1 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		32: ASM: vazkii.quark.content.experimental.module.GameNerfsModule@1dff2127 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		33: ASM: futurepack.common.FuturepackEventHandler@35d291fe onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		34: ASM: io.github.strikerrocker.vt.tweaks.BeehiveTooltips@18543127 onToolTipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		35: net.minecraftforge.eventbus.EventBus$$Lambda$2996/0x0000000800aa7330@331fa478
		36: ASM: top.theillusivec4.curios.client.ClientEventHandler@7299d754 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		37: ASM: shetiphian.multibeds.client.misc.EventHandlerClient@3c004e9d itemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		38: ASM: mekanism.client.render.RenderTickHandler@42a375db filterTooltips(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		39: ASM: class com.cursery.event.ClientEventHandler on(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		40: ASM: mcjty.lib.tooltips.TooltipRender@8a1ace6 onItemTooltipEvent(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		41: net.minecraftforge.eventbus.EventBus$$Lambda$2996/0x0000000800aa7330@202dda3d
		42: ASM: mcjty.lib.tooltips.TooltipRender@8a1ace6 onMakeTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		43: net.minecraftforge.eventbus.EventBus$$Lambda$2996/0x0000000800aa7330@667353d2
		44: ASM: wayoftime.bloodmagic.client.ClientEvents@7acf7bba appendTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		45: net.minecraftforge.eventbus.EventBus$$Lambda$2996/0x0000000800aa7330@1772260f
		46: LOW
		47: ASM: class com.supermartijn642.durabilitytooltip.DurabilityTooltipClient onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		48: ASM: com.blakebr0.cucumber.handler.TagTooltipHandler@1fa4f473 onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		49: ASM: com.blakebr0.cucumber.handler.NBTTooltipHandler@fa753b onItemTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		50: LOWEST
		51: ASM: class com.endertech.minecraft.forge.client.DevInfo onInventoryTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		52: ASM: com.aizistral.enigmaticlockbox.mALIGNitY@669a1240 ????(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		53: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@42bfd702 onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
		54: ASM: class mcp.mobius.waila.WailaClient onTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at TRANSFORMER/enchdesc@10.0.9/net.darkhax.enchdesc.DescriptionManager.getDescription(DescriptionManager.java:18)
	at TRANSFORMER/enchdesc@10.0.9/net.darkhax.enchdesc.EnchDescCommon.onItemTooltip(EnchDescCommon.java:50)
	at TRANSFORMER/bookshelf@13.2.50/net.darkhax.bookshelf.impl.event.EventHelperForge.lambda$addItemTooltipListener$0(EventHelperForge.java:23)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.1.80/net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:275)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:768)
	at TRANSFORMER/roughlyenoughitems@8.3.549/me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:226)
	at TRANSFORMER/roughlyenoughitems@8.3.549/me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:371)
	at TRANSFORMER/roughlyenoughitems@8.3.549/me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:211)
	at TRANSFORMER/roughlyenoughitems@8.3.549/me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:90)
	at TRANSFORMER/roughlyenoughitems@8.3.549/me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:75)
	at TRANSFORMER/roughlyenoughitems@8.3.549/me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.cacheData(TooltipArgumentType.java:45)
	at TRANSFORMER/roughlyenoughitems@8.3.549/me.shedaniel.rei.impl.client.search.argument.Argument.lambda$prepareFilter$0(Argument.java:302)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

### Gametype

Singleplayer

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
There's no support for 1.18. You have to be on 1.18.2 and on the latest or recommanded version.

**Comment by itsdinkd** [comment]
I am on 1.18.2 and using the latest version as I wrote above

##Minecraft Version

1.18.2


I put the wrong corail version tho. i am using 7.5.4

**Comment by Corail31** [comment]
The latest version is 7.5.4.

**Comment by itsdinkd** [comment]
I put the wrong corail version tho. i am using 7.5.4

**Comment by itsdinkd** [comment]
Can you re-open ticket so it doesn't get lost please 🙏

**Comment by Corail31** [comment]
Why do you think the concurrent is coming from Corail Tombstone ?
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at TRANSFORMER/enchdesc@10.0.9/net.darkhax.enchdesc.DescriptionManager.getDescription(DescriptionManager.java:18
```

**Comment by itsdinkd** [comment]
```
Listeners:
		0: HIGHEST
		1: ASM: class ovh.corail.tombstone.event.ClientEventHandler handleTooltip(Lnet/minecraftforge/event/entity/player/ItemTooltipEvent;)V
```
		
From this. If it has nothing to do with this then i apologize

**Comment by Corail31** [comment]
Yes, it's the event being called in highest priority but the code in Tombstone checks if the mod "enchdesc" is loaded and do nothing if it's ;)
NB: You can try to open an issue on Darkhax github if he knows the reason for this to happen with your current list of mods.
Also the **full log** would have been more helpful.

**Comment by itsdinkd** [comment]
> Yes, it's the event being called in highest priority but the code in Tombstone checks if the mod "enchdesc" is loaded and do nothing if it's ;) NB: You can try to open an issue on Darkhax github if he knows the reason for this to happen with your current list of mods. Also the **full log** would have been more helpful.

I see, makes sense now. 

Apologies ill post a full log next time.
