### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by AechtRob** [Corail31/tombstone_lite#92]
### Minecraft Version

1.12.2

### Forge Version

forge-1.12.2-14.23.5.2860.jar

### Corail Tombstone Version

4.5.8

### What happened?

When a MP server loads up I get this error and the server crashes. I have excerpted. Please let me know if you need more info:

java.lang.NoSuchMethodErrorovh.corail.tombstone.helper.LangKey.createText(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
[07.10 18:29:05] [Server] 	at ovh.corail.tombstone.item.ItemMagicScroll.func_77653_i(ItemMagicScroll.java:58) ~[ItemMagicScroll.class:?]
[07.10 18:29:05] [Server] 	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617) ~[aip.class:?]
[07.10 18:29:05] [Server] 	at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:1048) ~[aip.class:?]
[07.10 18:29:05] [Server] 	at net.minecraft.stats.StatList.func_75925_c(StatList.java:581) ~[qs.class:?]
[07.10 18:29:05] [Server] 	at net.minecraft.stats.StatList.func_151178_a(StatList.java:551) ~[qs.class:?]
[07.10 18:29:05] [Server] 	at net.minecraft.stats.StatList.reinit(StatList.java:694) ~[qs.class:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:586) ~[forge-1.12.2-14.23.5.2860.jar:14.23.5.2860]
[07.10 18:29:05] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
[07.10 18:29:05] [Server] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
[07.10 18:29:05] [Server] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
[07.10 18:29:05] [Server] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
[07.10 18:29:05] [Server] 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
[07.10 18:29:05] [Server] 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
[07.10 18:29:05] [Server] 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
[07.10 18:29:05] [Server] 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
[07.10 18:29:05] [Server] 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
[07.10 18:29:05] [Server] 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
[07.10 18:29:05] [Server] 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[LoadController.class:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[LoadController.class:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916) ~[Loader.class:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259) ~[GameData.class:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758) ~[Loader.class:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
[07.10 18:29:05] [Server] 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
[07.10 18:29:05] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
[07.10 18:29:05] [Server] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
[07.10 18:29:05] [Server] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
[07.10 18:29:05] [Server] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /./crash-reports/crash-2022-10-07_18.29.05-server.txt

### Gametype

Dedicated Server

### Happen by testing with only Corail Tombstone (required)

No

### Occurence

occurs all the time

### Tested without any Forge "alternatives" (Magma, Mohist, and so on)

- [X] Yes

### Valid Launcher

- [X] Yes

**Comment by Corail31** [comment]
Thanks for reporting this issue. This is fixed in release 4.5.9
